name: Post to API on Push

on:
  push:

jobs:
  post_to_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send POST request to API
        run: |
          curl -X POST https://api-activdad-actions.onrender.com/alumnos \
          -H "Content-Type: application/json" \
          -d '{"nombre": "Cristóbal", "apellido": "Moreno", "pelicula_favorita": "Avengers"}'
